# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Diagnostic
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          echo "Which java:"
          which java
          java -version

          echo "Which mvn:"
          which mvn
          mvn -version

      - name: Build with Maven (force JDK 21)
        run: |
          export JAVA_HOME=$JAVA_HOME
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version
          mvn -B clean package --file pom.xml

      - name: Publish to GitHub Packages (force JDK 21)
        run: |
          export JAVA_HOME=$JAVA_HOME
          export PATH="$JAVA_HOME/bin:$PATH"
          mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
